//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSConsoleStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingStatusHistory
    {
        public int MeetingHistoryId { get; set; }
        public int MeetingId { get; set; }
        public int MeetingStatusId { get; set; }
        public System.DateTime LasteUpdatedAt { get; set; }
        public string Remarks { get; set; }
        public string UserEmail { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual MeetingStatu MeetingStatu { get; set; }
    }
}
