//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSConsoleStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VMSEntities : DbContext
    {
        public VMSEntities()
            : base("name=VMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<MeetingStatu> MeetingStatus { get; set; }
        public virtual DbSet<Organizer> Organizers { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<MeetingStatusHistory> MeetingStatusHistories { get; set; }
    
        public virtual int spCreateMeeting(Nullable<int> organizerId, string visitorEmail, string contactNumber, Nullable<System.DateTime> scheduledDate, string purpose)
        {
            var organizerIdParameter = organizerId.HasValue ?
                new ObjectParameter("OrganizerId", organizerId) :
                new ObjectParameter("OrganizerId", typeof(int));
    
            var visitorEmailParameter = visitorEmail != null ?
                new ObjectParameter("VisitorEmail", visitorEmail) :
                new ObjectParameter("VisitorEmail", typeof(string));
    
            var contactNumberParameter = contactNumber != null ?
                new ObjectParameter("ContactNumber", contactNumber) :
                new ObjectParameter("ContactNumber", typeof(string));
    
            var scheduledDateParameter = scheduledDate.HasValue ?
                new ObjectParameter("ScheduledDate", scheduledDate) :
                new ObjectParameter("ScheduledDate", typeof(System.DateTime));
    
            var purposeParameter = purpose != null ?
                new ObjectParameter("Purpose", purpose) :
                new ObjectParameter("Purpose", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCreateMeeting", organizerIdParameter, visitorEmailParameter, contactNumberParameter, scheduledDateParameter, purposeParameter);
        }
    }
}
