//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS_Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public Visitor()
        {
            this.Meetings = new HashSet<Meeting>();
        }
    
        public int VisitorId { get; set; }
        public string EmailId { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual ICollection<Meeting> Meetings { get; set; }
    }
}
